language : node_js
node_js :
 - stable
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
install:
 - yarn install
script:
 - yarn test-ci
 - yarn lint